[package]
name = "picture-audit"
version = "0.1.0"
authors = ["jared b <jaredcbaum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"